import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';import path from 'node:path';
const root=path.dirname(fileURLToPath(import.meta.url));
const read=async f=>(await readFile(path.join(root,f),'utf8')).replace(/\r\n?/g,'\n');
let html=await read('dist/index.html');const css=await read('dist/style.css'),vendor=await read('dist/vendor/jszip.min.js');
const engine=await read('dist/engine.js');const names=[...engine.matchAll(/export\s+(?:async\s+)?(?:const|function)\s+(\w+)/g)].map(m=>m[1]);
const io=(await read('dist/xlsx.js')).replace(/^import[^\n]*\n/,'');const app=(await read('dist/app.js')).replace(/^import[^\n]*\n/gm,'').replace(/export\s+/g,'').replace('const E={...B,...P};','');
const columns=(await read('dist/columns.js')).replace(/^import[^\n]*\n/,'').replace(/export\s+/g,'');
const rental=(await read('dist/rental.js')).replace(/^import[^\n]*\n/gm,'');
const rentalNames=[...rental.matchAll(/export\s+(?:const|function)\s+(\w+)/g)].map(m=>m[1]);
const indexModule=await read('dist/indices.js');
const indexNames=[...indexModule.matchAll(/export\s+(?:const|function)\s+(\w+)/g)].map(m=>m[1]);
const properties=(await read('dist/properties.js')).replace(/^import[^\n]*\n/gm,'');
const propertyNames=[...properties.matchAll(/export\s+(?:const|function)\s+(\w+)/g)].map(m=>m[1]);
const rateData=await read('dist/rates.js');
const wrap=async(file,id)=>{const module=(await read(file)).replace(/^import[^\n]*\n/gm,'');const exports=[...module.matchAll(/export\s+(?:async\s+)?(?:const|function)\s+(\w+)/g)].map(m=>m[1]);return 'const '+id+'=(()=>{'+module.replace(/export\s+/g,'')+'\nreturn {'+exports.join(',')+'};})();\n';};
const households=await wrap('dist/household-match.js','H'),report=await wrap('dist/report.js','Q'),householdQuery=(await wrap('dist/household-query.js','HQ'))+'const {queryHouseholds}=HQ;\n',reportView=(await wrap('dist/report-view.js','V'))+'const {bindReport}=V;\n';
const script=rateData+'\n'+vendor+'\n;const B=(()=>{'+engine.replace(/export\s+/g,'')+'\nreturn {'+names.join(',')+'};})();\nconst E={...B};\n'+columns+'\nconst P=(()=>{'+properties.replace(/export\s+/g,'')+'\nreturn {'+propertyNames.join(',')+'};})();Object.assign(E,P);\nconst {readXlsx,exportXlsx}=(()=>{const {REQUIRED,find,header}=E;'+io.replace(/export\s+/g,'')+'\nreturn {readXlsx,exportXlsx};})();\n'+'\nconst R=(()=>{'+rental.replace(/export\s+/g,'')+'\nreturn {'+rentalNames.join(',')+'};})();\n'+'const I=(()=>{'+indexModule.replace(/export\s+/g,'')+'\nreturn {'+indexNames.join(',')+'};})();\n'+households+householdQuery+report+reportView+'\n'+app;
const digest=createHash('sha256').update(script).digest('base64');
html=html.replace('script-src \'self\'','script-src \'sha256-'+digest+'\'').replace('<link rel="stylesheet" href="./style.css">',()=>'<style>'+css+'</style>').replace('<script defer src="./vendor/jszip.min.js"></script>','').replace('<script defer src="./rates.js"></script>','').replace('<script defer src="./households.js"></script>','').replace('<script type="module" src="./app.js"></script>','').replace('</body>',()=>'<script>'+script+'</script></body>');
await writeFile(path.join(root,'offline.html'),html);await writeFile(path.join(root,'dist/offline.html'),html);console.log('offline.html created');
