import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';import * as E from '../dist/engine.js';
const app=readFileSync(new URL('../dist/app.js',import.meta.url),'utf8');const fn=app.slice(app.indexOf('async function loadFiles('),app.indexOf('function refreshPeriods('));
const source=(name,values)=>({name,headers:['NO','값'],metadata:{'실거래 구분':'아파트(매매)'},rows:values.map((v,i)=>({rowNumber:i+1,cells:[i+1,v]}))});
function harness(state,success=true){const messages=[];let loaded=null;const catalog=new Map(),datasetKey=s=>(s.headers.includes('보증금')?'rent':'sale')+':'+(s.metadata['실거래 구분'].includes('오피스텔')?'오피스텔':'아파트'),saveDataset=()=>{if(state.source)catalog.set(datasetKey(state.source),{...state})};const c=vm.createContext({state,catalog,datasetKey,saveDataset,propertyUI:()=>{},R:{rentalSource:s=>s.headers.includes('보증금'),parseRental:()=>{throw Error('전월세 필수 열 누락')}},rates:{},E:{...E,parseRows:()=>[]},I:{isIndexSource:()=>false},indexActive:false,busy:v=>state.busy=v,readXlsx:async f=>f,notify:(...m)=>messages.push(m),$:()=>({}),loadFile:async(f,s,p)=>{loaded={s,p};if(success)state.source=s;return success;}});vm.runInContext(fn+';globalThis.run=loadFiles;',c);return {c,messages,get loaded(){return loaded;}};}
test('append reuses original sources, deduplicates overlaps, preserves manual policy and rates',async()=>{const a=source('a',[1,2,2]),b=source('b',[2,2,3]);const state={source:E.mergeSources([a]),sources:[a],salePolicy:{direct:true,outside:false},manualRates:{x:4},manual:new Set(['raw-1-0'])};const h=harness(state);await h.c.run([b],true);assert.equal(h.loaded.s.rows.length,4);assert.equal(h.loaded.s.duplicates,2);assert.equal(state.sources.length,2);assert.equal(h.loaded.p.salePolicy.direct,true);assert.ok(h.loaded.p.manual.has('raw-1-0'));await h.c.run([b],true);assert.equal(h.loaded.s.rows.length,4);assert.equal(state.sources.length,3);});
test('replace resets source list; failure does not report success or replace previous sources',async()=>{const a=source('a',[1]),b=source('b',[2]);const state={source:a,sources:[a]};const h=harness(state);await h.c.run([b]);assert.equal(state.sources[0],b);assert.equal(h.loaded.p,null);const failed=harness(state,false);await failed.c.run([a],true);assert.equal(state.sources.length,1);assert.equal(failed.messages.length,0);});
test('invalid rental addition retains existing data',async()=>{const a=source('a',[1]),b={...source('b',[2]),headers:['보증금']};const state={source:a,sources:[a]};const h=harness(state);await h.c.run([b],true);assert.equal(h.loaded,null);assert.equal(state.source,a);assert.equal(h.messages[0][1],true);});

test('mixed type open and append retain current result',async()=>{const a=source('a',[1]),b={...source('b',[2]),metadata:{'실거래 구분':'오피스텔(매매)'}};for(const append of [false,true]){const state={source:a,sources:[a]},h=harness(state);await h.c.run(append?[b]:[a,b],append);assert.equal(h.loaded,null);assert.equal(state.source,a);assert.equal(state.sources[0],a);assert.equal(h.messages.at(-1)[1],true);}});
