import test from 'node:test';
import assert from 'node:assert/strict';
import * as P from '../dist/properties.js';
const source=(kind,items)=>({name:kind+'(매매).xlsx',metadata:{'실거래 구분':kind},headers:['NO','시군구','유형','지번','건물명','단지명','주택유형','전용면적(㎡)','전용/연면적(㎡)','연면적(㎡)','대지면적(㎡)','거래금액(만원)','층','건축물주용도','계약년월','계약일','거래유형','중개사소재지','해제사유발생일','지분구분'],rows:items.map((r,i)=>({rowNumber:i+14,cells:[i+1,'서울특별시 마포구 합정동','집합','12','빌라','단지','다세대',59.28,100,100,50,100000,'1','업무','202601','02','중개거래','서울 마포구','-',''].map((v,j)=>r[j]??v)}))});
test('villa has no type column and retains exact area grouping',()=>{const s=source('연립다세대',[{}, {7:59.49}]);const r=P.parseRows(s);assert.equal(P.aggregate(r).apartments.length,2);for(const cols of Object.values(P.columns('연립다세대')))assert.ok(!cols.some(c=>['type','typeText'].includes(c.key)));});
test('nonresidential floors and ownership categories never mix',()=>{const r=P.parseRows(source('상업업무용',[{}, {12:'2'}, {2:'일반'}]));assert.equal(P.aggregate(r).apartments.length,3);assert.ok(P.columns('공장창고등').apartments.some(c=>c.key==='floor'));assert.equal(r[0].landUnitPrice,null);assert.ok(r[2].landUnitPrice>0);});
test('missing area preserves prices and counts, shares remain excluded',()=>{const r=P.parseRows(source('공장창고등',[{8:'',10:''},{19:'지분',16:'직거래'}]));const a=P.aggregate(P.salePolicyRows(r,{direct:true,outside:true}));assert.equal(a.included.length,1);assert.equal(a.apartments[0].priceAverage,100000);assert.equal(a.apartments[0].average,null);assert.equal(a.excluded[0].reason,'지분 거래');});
test('masked duplicates preserved and different property types rejected',()=>{const s=source('단독다가구',[{3:'1**'}]);const m=P.mergeSources([s,{...s,name:'단독다가구2.xlsx'}]);assert.equal(m.rows.length,2);assert.equal(m.duplicateCandidates,1);assert.throws(()=>P.mergeSources([s,source('상업업무용',[{}])]));});
test('period statistics reconcile and filters include floor and numeric ranges',()=>{const r=P.parseRows(source('상업업무용',[{}, {12:'2'}]));assert.equal(P.filtered(r,{floor:new Set(['2']),areaMin:90}).length,1);const a=P.periodAnalysis(r,'property','month','2026-01-01','2026-03-31');assert.equal(a.rows.length,6);assert.equal(a.rows.reduce((n,r)=>n+r.count,0),2);assert.equal(a.rows.filter(r=>r.count===0).length,4);});
