import test from 'node:test';import assert from 'node:assert/strict';import * as E from '../dist/engine.js';
const rows=[{id:'a',name:'A',address:'서울 1',type:59,area:59,year:'2000',date:'2026-01-01',price:100,unitPrice:10,reason:'포함'},{id:'b',name:'A',address:'서울 1',type:59,area:59,year:'2000',date:'2026-01-02',price:300,unitPrice:30,reason:'포함'},{id:'c',name:'A',address:'서울 1',type:59,area:59,reason:'직거래'}];
test('manual exclusion updates averages, trend and restores without mutating source',()=>{const effective=E.reviewedRows(rows,new Set(['b','c']));assert.equal(E.aggregate(effective).apartments[0].average,10);assert.equal(E.trend(effective,E.propertyKey(rows[0]),null,'month').trades.length,1);assert.equal(effective[2].reason,'직거래');assert.equal(rows[1].reason,'포함');assert.equal(E.aggregate(E.reviewedRows(rows,new Set())).apartments[0].average,20);assert.equal(E.aggregate(E.reviewedRows(rows,new Set(['a','b']))).included.length,0);});
test('unit toggles preserve ranges and do not alter names or prices',()=>{const off={'평':false,'㎡':false,'타입':false};assert.equal(E.unitValue('59.01~59.99㎡','areaText',off),'59.01~59.99');assert.equal(E.unitValue('17.85평','pyeongText',off),'17.85');assert.equal(E.unitValue('59타입','typeText',off),'59');assert.equal(E.unitValue(59.5,'area',{}),'59.5㎡');assert.equal(E.unitValue('평아파트','name',off),'평아파트');assert.equal(E.unitValue(300,'average',off),300);});
test('optional sale inclusions retain cancellations, invalid data and manual exclusions',()=>{
 const direct={...rows[0],id:'direct',reason:'직거래',region:'서울 용산구'};const outside={...direct,id:'outside',reason:'타지역 중개사'};const cancelled={...direct,id:'cancel',reason:'해제 거래'};const bad={...direct,id:'bad',area:0};const input=[direct,outside,cancelled,bad];
 assert.equal(E.salePolicyRows(input).filter(r=>r.reason==='포함').length,0);
 const enabled=E.salePolicyRows(input,{direct:true,outside:true});assert.equal(enabled.filter(r=>r.reason==='포함').length,2);assert.equal(enabled[2].reason,'해제 거래');assert.equal(enabled[3].reason,'입력값 확인');assert.equal(E.reviewedRows(enabled,new Set(['direct']))[0].reason,'수동 제외');assert.equal(input[0].reason,'직거래');
});
